arb-dir: assets/l10n # The directory where the template and translated arb files are located
output-dir: lib/gen/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false # have to be false for custom output-dir
