name: expenso
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.2
  path: ^1.8.3
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  circular_countdown_timer: ^0.2.3
  group_list_view: ^1.1.1
  path_provider: ^2.1.2
  syncfusion_flutter_charts: ^25.1.37
  focused_menu: ^1.0.5
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  awesome_notifications: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  objectbox_generator: any

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/barChartIcon.png
    - assets/settingsIcon.png
    - assets/barModeIcon.png
    - assets/barChartPlug.png
    - assets/donutModeIcon.png
    - assets/donutChartPlug.png
    - assets/calendarIcon.png
    - assets/refreshIcon.png
    - assets/welcome/welcome1.png
    - assets/welcome/welcome2.png
    - assets/welcome/welcome3_ru.png
    - assets/welcome/welcome4_ru.png
    - assets/welcome/welcome6_ru.png
    - assets/welcome/welcome3_en.png
    - assets/welcome/welcome4_en.png
    - assets/welcome/welcome6_en.png
    - assets/welcome/welcomeDark1.png
    - assets/welcome/welcomeDark2.png
    - assets/welcome/welcomeDark3_ru.png
    - assets/welcome/welcomeDark4_ru.png
    - assets/welcome/welcomeDark6_ru.png
    - assets/welcome/welcomeDark3_en.png
    - assets/welcome/welcomeDark4_en.png
    - assets/welcome/welcomeDark6_en.png
    - assets/calendarMonthBackground.png
    - assets/calendarWeekBackground.png

  fonts:
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Black.otf
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
