name: expenso
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.2
  path: ^1.8.3
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  circular_countdown_timer: ^0.2.3
  # grouped_list: ^5.1.2
  group_list_view: ^1.1.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/barChartIcon.png
    - assets/settingsIcon.png
